import { ChartNoAxesColumnIncreasing, Flame, Sparkles } from "lucide-react";
import type { DiaryMood } from "@/lib/api/diary-api";
import { MOOD_META } from "@/lib/mood-meta";
import { buildWeeklyRhythmNarrative, isSameLocalDay, type ActivityDay } from "@/features/insights/memory-insights";

export function WeeklyRhythmWidget({ weekEntries, activeDays, streak, mood, recentDays, isLoading }: { weekEntries: number; activeDays: number; streak: number; mood: DiaryMood | null; recentDays: ActivityDay[]; isLoading: boolean }) {
  const MoodIcon = mood ? MOOD_META[mood].icon : Sparkles;
  const maxCount = Math.max(1, ...recentDays.map((day) => day.count));
  const narrative = buildWeeklyRhythmNarrative({ weekEntries, activeDays, mood, recentDays });
  return <article className="enterprise-card flex min-w-0 flex-col p-5"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-[13px] font-semibold text-cyan-700 dark:text-cyan-300"><ChartNoAxesColumnIncreasing className="h-4 w-4" />Weekly rhythm</p><h2 className="mt-1 text-lg font-semibold text-slate-950 dark:text-white">Keep the thread going</h2></div>{streak ? <span className="status-badge border-pink-200 bg-pink-50 text-pink-700 dark:border-pink-900 dark:bg-pink-950/40 dark:text-pink-200"><Flame className="h-3.5 w-3.5" />{streak} day streak</span> : null}</div><div className="mt-4 grid grid-cols-3 border-y border-slate-200 py-2.5 text-center dark:border-slate-800"><Metric value={isLoading ? "..." : `${weekEntries}`} label="Memories" /><Metric value={isLoading ? "..." : `${activeDays}`} label="Active days" divided /><div className="min-w-0 px-1"><p className="flex items-center justify-center gap-1.5 truncate text-sm font-bold text-slate-950 dark:text-white"><MoodIcon className={`h-4 w-4 ${mood ? MOOD_META[mood].iconClassName : "text-slate-400"}`} /><span className="truncate">{mood ? MOOD_META[mood].label : "No mood"}</span></p><p className="mt-1 text-xs text-slate-500">This week</p></div></div><p className="mt-4 border-l-2 border-cyan-200 pl-3 text-sm leading-6 text-slate-600 dark:border-cyan-900 dark:text-slate-300">{isLoading ? "Reading this week's rhythm..." : narrative}</p><div className="mt-3 grid flex-1 grid-cols-7 gap-1.5" aria-label="Memory activity over the last seven days">{recentDays.map((day) => { const today = isSameLocalDay(day.date, new Date()); const height = day.count ? Math.max(24, Math.round((day.count / maxCount) * 48)) : 8; return <div key={day.date.toISOString()} className="flex min-w-0 flex-col items-center justify-end gap-1.5"><span className="text-[11px] font-semibold text-slate-400">{day.count || ""}</span><span className={`w-full max-w-7 rounded-sm ${day.count ? today ? "bg-indigo-500" : "bg-cyan-400 dark:bg-cyan-600" : "bg-slate-200 dark:bg-slate-800"}`} style={{ height }} /><span className={`text-[11px] font-semibold ${today ? "text-indigo-600" : "text-slate-500"}`}>{new Intl.DateTimeFormat(undefined, { weekday: "narrow" }).format(day.date)}</span></div>; })}</div></article>;
}

function Metric({ value, label, divided = false }: { value: string; label: string; divided?: boolean }) {
  return <div className={divided ? "border-x border-slate-200 dark:border-slate-800" : ""}><p className="text-xl font-bold text-slate-950 dark:text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>;
}
